function testTest () {
    try {
        
    } catch (error) {
        return error.error
    }
    return 
}

console.log(testTest());